# Generated by Django 2.2.28 on 2024-06-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('reference', models.CharField(blank=True, max_length=128, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('donation_made', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
